const ma71ItemCategoryData = [
    {id:17, name:'禮包開出的物品',eng:'Wanted Items'},
    {id:191, name:'遊戲內貨幣與出售物品',eng:'Objects'},
    {id:156, name:'寵物',eng:'Dog'},
    {id:18, name:'背包',eng:'Bagpack'},
    {id:93, name:'套裝',eng:'Clothing'},
    {id:73, name:'食物',eng:'Food'},
    {id:189, name:'基本材料',eng:'Base Ingredients'},
    {id:235, name:'旅途掉落',eng:'Biome Specific'},
    {id:221, name:'起始道具',eng:'Starting Items'},
    {id:653, name:'可出售商品',eng:'Valuables'},
    {id:112, name:'配方',eng:'Recipes'},
    {id:184, name:'工具',eng:'Mini-game Tools'},
    {id:185, name:'傢俱',eng:'furniture'},
    {id:186, name:'牆上傢俱',eng:'Wall'},
    {id:187, name:'地面傢俱',eng:'Floor'},
    {id:199, name:'機器',eng:'Machines'},
    {id:295, name:'家居裝飾品',eng:'Accessories'},
    {id:879, name:'小鎮裝飾',eng:'Town Deco'},
  ];

const ma71ItemData = {
    //傢俱
    185:[
      {itemId:196, itemName:'共用物品架',ItemNameEng:'Shared Shelving'},
      {itemId:12, itemName:'公告黑板',ItemNameEng:'Communal Blackboard'},
      {itemId:164, itemName:'黑板',ItemNameEng:'Blackboard'},
      {itemId:180, itemName:'簡單扶手椅',ItemNameEng:'Simple Chair'},
      {itemId:198, itemName:'小桌子',ItemNameEng:'Small Table'},
      {itemId:306, itemName:'節日蠟燭',ItemNameEng:'Festive Candles'},
      {itemId:612, itemName:'簡單扶手椅',ItemNameEng:'Simple Armchair'},
      {itemId:688, itemName:'酒館扶手椅',ItemNameEng:'Saloon Armchair'},
      {itemId:299, itemName:'長襪',ItemNameEng:'Stocking'},
      {itemId:20, itemName:'簡單的扶手椅',ItemNameEng:'Simple Armchair'},
      {itemId:27, itemName:'簡單的扶手椅',ItemNameEng:'Simple Armchair'},
      {itemId:192, itemName:'酒吧桌',ItemNameEng:'Saloon Table'},
      {itemId:255, itemName:'酒館床鋪',ItemNameEng:'Saloon Bed'},
      {itemId:690, itemName:'豪華大床',ItemNameEng:'Luxury Bed'},
      {itemId:695, itemName:'鄉村風地毯',ItemNameEng:'Native Rug'},
      {itemId:258, itemName:'豪華櫥櫃',ItemNameEng:'Luxury Cupboard'},
      {itemId:91, itemName:'鍋具',ItemNameEng:'Pots and Pans'},
      {itemId:95, itemName:'移動茶桌',ItemNameEng:'Tea Trolley'},
      {itemId:49, itemName:'小號保險櫃',ItemNameEng:'Private Chest'},
      {itemId:300, itemName:'花環',ItemNameEng:'Wreath'},
      {itemId:301, itemName:'紙環鏈',ItemNameEng:'Paper Chains'},
      {itemId:175, itemName:'裝飾用桌子',ItemNameEng:'Decorative Table'},
      {itemId:193, itemName:'簡單的床',ItemNameEng:'Simple Bed'},
      {itemId:212, itemName:'臥室書桌',ItemNameEng:'Bedroom Shelves'},
      {itemId:230, itemName:'大鏡子',ItemNameEng:'Large Mirror'},
      {itemId:430, itemName:'中號保險櫃',ItemNameEng:'Medium Chest'},
      {itemId:241, itemName:'狗地毯',ItemNameEng:'Dog Rug'},
      {itemId:172, itemName:'廚房椅',ItemNameEng:'Kitchen Chair'},
      {itemId:302, itemName:'節日彩燈',ItemNameEng:'Festive Lights'},
      {itemId:305, itemName:'節日禮物',ItemNameEng:'Festive Gifts'},
      {itemId:622, itemName:'廚房碗櫃',ItemNameEng:'Kitchen Cupboard'},
      {itemId:696, itemName:'廚房桌',ItemNameEng:'Kitchen Table'},
      {itemId:6, itemName:'屏風',ItemNameEng:'Privacy Screen'},
      {itemId:36, itemName:'榻榻米',ItemNameEng:'Japanese Tatami'},
      {itemId:144, itemName:'浴桶',ItemNameEng:'Barrel Bathtub'},
      {itemId:260, itemName:'水槽',ItemNameEng:'Sink'},
      {itemId:262, itemName:'鄉土風沙發',ItemNameEng:'Native Sofa'},
      {itemId:271, itemName:'馬桶',ItemNameEng:'Toilet'},
      {itemId:431, itemName:'大號保險櫃',ItemNameEng:'Large Chest'},
      {itemId:533, itemName:'鄉土風扶手椅',ItemNameEng:'Native Armchair'},
      {itemId:14, itemName:'烤箱',ItemNameEng:'Oven'},
      {itemId:190, itemName:'地球儀',ItemNameEng:'Earth Globe'},
      {itemId:183, itemName:'鋼琴',ItemNameEng:'Piano'},
      {itemId:194, itemName:'畫架',ItemNameEng:'Easel'},
      {itemId:204, itemName:'留聲機',ItemNameEng:'Gramophone'},
      {itemId:208, itemName:'吉他',ItemNameEng:'Guitar'},
      {itemId:178, itemName:'檯燈',ItemNameEng:'Desk Lamp'},
      {itemId:216, itemName:'圖書館',ItemNameEng:'Library'},
      {itemId:267, itemName:'寫字臺',ItemNameEng:'Writing Desk'},
      {itemId:32, itemName:'日式被褥',ItemNameEng:'Japanese Futon'},
      {itemId:33, itemName:'日式屏風',ItemNameEng:'Japanese Screen'},
      {itemId:35, itemName:'日式炬燵',ItemNameEng:'Japanese Kotatsu'},
      {itemId:151, itemName:'豪華大床',ItemNameEng:'Luxury Bed'},
      {itemId:303, itemName:'聖誕樹',ItemNameEng:'Festive Tree'},
      {itemId:88, itemName:'斑馬紋地毯',ItemNameEng:'Zebra Print Rug'},
      {itemId:238, itemName:'地球儀紅酒架',ItemNameEng:'Globe Bar'},
      {itemId:240, itemName:'象棋桌',ItemNameEng:'Chess Table'},
      {itemId:202, itemName:'浴缸',ItemNameEng:'Bathtub'},
      {itemId:410, itemName:'東方燈籠',ItemNameEng:'Oriental Lantern'},
      {itemId:40, itemName:'派對氣球',ItemNameEng:'Party Balloons'},
      {itemId:66, itemName:'口香糖販賣機',ItemNameEng:'Gumball Machine'},
      {itemId:68, itemName:'斑馬紋扶手椅',ItemNameEng:'Zebra Print Armchair'},
      {itemId:79, itemName:'斑馬紋沙發',ItemNameEng:'Zebra Print Sofa'},
      {itemId:232, itemName:'檯球桌',ItemNameEng:'Billiard Table'},
      {itemId:239, itemName:'彈球機',ItemNameEng:'Pinball Machine'},
      {itemId:285, itemName:'藤蔓',ItemNameEng:'Hanging Vines'},
      {itemId:298, itemName:'盆栽',ItemNameEng:'Potted Trees'},
      {itemId:265, itemName:'魚缸',ItemNameEng:'Fish Tank'},
      {itemId:282, itemName:'水飾',ItemNameEng:'Water Feature'},
      {itemId:407, itemName:'東方椅子',ItemNameEng:'Oriental Chair'},
      {itemId:408, itemName:'東方圓桌',ItemNameEng:'Oriental Round Table'},
      {itemId:409, itemName:'東方錦鯉噴泉',ItemNameEng:'Oriental Koi Fountain'},
      {itemId:426, itemName:'遠古床',ItemNameEng:'Skeleton Bed'},
      {itemId:427, itemName:'遠古椅',ItemNameEng:'Skeleton Chair'},
      {itemId:429, itemName:'恐龍模型',ItemNameEng:'Model Dinosaur'},
      {itemId:432, itemName:'遠古燈',ItemNameEng:'Skeleton Lamp'},
      {itemId:433, itemName:'航海炮',ItemNameEng:'Pirate Cannon'},
      {itemId:434, itemName:'航海旗',ItemNameEng:'Pirate Flag'},
      {itemId:435, itemName:'航海舷窗',ItemNameEng:'Pirate Porthole'},
      {itemId:436, itemName:'航海圖騰',ItemNameEng:'Pirate Totem'},
      {itemId:438, itemName:'航海方向盤',ItemNameEng:'Pirate Wheel'},
      {itemId:510, itemName:'裝飾蛋',ItemNameEng:'Ornamental Egg'},
      {itemId:511, itemName:'水仙花',ItemNameEng:'Daffodils'},
      {itemId:512, itemName:'萌兔椅',ItemNameEng:'Bunny Chair'},
      {itemId:513, itemName:'小兔地毯',ItemNameEng:'Bunny Carpet'},
      {itemId:602, itemName:'沙灘陽傘',ItemNameEng:'Beach Parasol'},
      {itemId:603, itemName:'沙灘吧台',ItemNameEng:'Beach Bar'},
      {itemId:604, itemName:'花園椅',ItemNameEng:'Beach Chair'},
      {itemId:605, itemName:'花園桌',ItemNameEng:'Beach Table'},


    ],
    //牆上傢俱
    186:[
      {itemId:8, itemName:'窗戶',ItemNameEng:'Window'},
      {itemId:181, itemName:'紳士檯燈',ItemNameEng:'Gentleman\'s Lamp'},
      {itemId:621, itemName:'掛壁鹿角',ItemNameEng:'Wall Horns'},
      {itemId:209, itemName:'豪華燈具',ItemNameEng:'Luxury Lamp'},
      {itemId:263, itemName:'勺子收藏',ItemNameEng:'Spoon Collection'},
      {itemId:685, itemName:'酒紅窗簾',ItemNameEng:'Saloon Curtains'},
      {itemId:201, itemName:'相框',ItemNameEng:'Picture Frame'},
      {itemId:215, itemName:'毛巾',ItemNameEng:'Towel'},
      {itemId:266, itemName:'獵人戰利品',ItemNameEng:'Hunter Trophy'},
      {itemId:687, itemName:'酒館檯燈',ItemNameEng:'Saloon Lamp'},
      {itemId:691, itemName:'豪華窗簾',ItemNameEng:'Luxury Curtains'},
      {itemId:200, itemName:'水瓶',ItemNameEng:'Bottles'},
      {itemId:242, itemName:'中號鏡子',ItemNameEng:'Medium Mirror'},
      {itemId:244, itemName:'肖像畫',ItemNameEng:'Portrait Picture'},
      {itemId:243, itemName:'風景畫',ItemNameEng:'Landscape Picture'},
      {itemId:694, itemName:'豪華鏡子',ItemNameEng:'Luxury Mirror'},
      {itemId:686, itemName:'酒館飛鏢遊戲',ItemNameEng:'Saloon Dart Game'},
      {itemId:437, itemName:'布穀鳥鐘',ItemNameEng:'Cuckoo Clock'},
      {itemId:247, itemName:'壁爐',ItemNameEng:'Fireplace'},


    ],
    //地面傢俱
    187:[
      {itemId:616, itemName:'簡易地毯',ItemNameEng:'Simple Rug'},
      {itemId:614, itemName:'工程師地毯',ItemNameEng:'Engineer\'s Rug'},
      {itemId:197, itemName:'酒館地毯',ItemNameEng:'Saloon Rug'},
      {itemId:203, itemName:'紳士地毯',ItemNameEng:'Gentleman\'s Rug'},
      {itemId:97, itemName:'鄉土小地毯',ItemNameEng:'Small Native Rug'},
      {itemId:195, itemName:'豪華地毯',ItemNameEng:'Luxury Rug'},
      {itemId:105, itemName:'鄉村風地毯',ItemNameEng:'Native Carpet'},
      {itemId:108, itemName:'彩色地毯',ItemNameEng:'Colourful Carpet'},
    ],
    //機器
    199:[
      {itemId:293, itemName:'磨輪',ItemNameEng:'Grinding Wheel'},
      {itemId:294, itemName:'熔爐',ItemNameEng:'Smelter'},
      {itemId:634, itemName:'鋸床',ItemNameEng:'Saw Bench'},
      {itemId:636, itemName:'織布機',ItemNameEng:'Loom'},
      {itemId:637, itemName:'曬架',ItemNameEng:'Tanning Frame'},


    ],
    //家居裝飾品
    295:[
      {itemId:245, itemName:'蘆薈',ItemNameEng:'Aloe Vera'},
      {itemId:165, itemName:'蠟燭',ItemNameEng:'Candles'},
      {itemId:254, itemName:'棕櫚樹',ItemNameEng:'Palm Tree'},
      {itemId:188, itemName:'菜肴',ItemNameEng:'Dishes'},
      {itemId:246, itemName:'盆栽',ItemNameEng:'Bonsai'},
      {itemId:535, itemName:'書',ItemNameEng:'Books'},
      {itemId:182, itemName:'異國花盆',ItemNameEng:'Exotic Flowerpot'},
      {itemId:173, itemName:'粉色坐墊',ItemNameEng:'Pink Cushion'},
      {itemId:174, itemName:'紅色坐墊',ItemNameEng:'Red Cushion'},
      {itemId:250, itemName:'劍蘭',ItemNameEng:'Gladiolus'},
      {itemId:264, itemName:'編織籃',ItemNameEng:'Woven Basket'},
      {itemId:248, itemName:'仙人掌',ItemNameEng:'Cactus'},
      {itemId:411, itemName:'櫻花花瓶',ItemNameEng:'Cherry Blossom Vase'},
      {itemId:166, itemName:'熊雕',ItemNameEng:'Carved Bear'},
    ],
    93:[
      {itemId:547, itemName:'英倫褲子',ItemNameEng:'British Leggings'},
      {itemId:548, itemName:'英倫帽子',ItemNameEng:'British Tricorn'},
      {itemId:549, itemName:'英倫夾克',ItemNameEng:'British Jacket'},
      {itemId:550, itemName:'英倫靴子',ItemNameEng:'British Boots'},
      {itemId:103, itemName:'厚皮帽',ItemNameEng:'Thick Fur Hat'},
      {itemId:149, itemName:'厚皮靴',ItemNameEng:'Thick Fur Boots'},
      {itemId:153, itemName:'厚皮衣',ItemNameEng:'Thick Fur Coat'},
      {itemId:129, itemName:'荒野斗篷',ItemNameEng:'Wilderness Capote'},
      {itemId:158, itemName:'荒野褲子',ItemNameEng:'Wilderness Pants'},
      {itemId:161, itemName:'荒野靴子',ItemNameEng:'Wilderness Boots'},
      {itemId:167, itemName:'荒野帽子',ItemNameEng:'Wilderness Hat'},
      {itemId:399, itemName:'傭兵褲子',ItemNameEng:'Mercenary Pants'},
      {itemId:400, itemName:'傭兵帽子',ItemNameEng:'Mercenary Hat'},
      {itemId:401, itemName:'傭兵襯衫',ItemNameEng:'Mercenary Shirt'},
      {itemId:402, itemName:'傭兵靴子',ItemNameEng:'Mercenary Boots'},
      {itemId:297, itemName:'熱帶涼鞋',ItemNameEng:'Tropical Sandals'},
      {itemId:376, itemName:'熱帶褲子',ItemNameEng:'Tropical Pants'},
      {itemId:377, itemName:'熱帶帽子',ItemNameEng:'Tropical Hat'},
      {itemId:378, itemName:'熱帶襯衫',ItemNameEng:'Tropical Shirt'},
      {itemId:391, itemName:'遊牧民褲子',ItemNameEng:'Nomad Pants'},
      {itemId:392, itemName:'遊牧民圍巾',ItemNameEng:'Nomad Scarf'},
      {itemId:393, itemName:'遊牧民頭巾',ItemNameEng:'Nomad Turban'},
      {itemId:394, itemName:'遊牧民拖鞋',ItemNameEng:'Nomad Slipper'},
      {itemId:31, itemName:'警長靴',ItemNameEng:'Sheriff Boots'},
      {itemId:44, itemName:'警長背心',ItemNameEng:'Sheriff Vest'},
      {itemId:80, itemName:'警長帽子',ItemNameEng:'Sheriff Hat'},
      {itemId:109, itemName:'警長皮褲',ItemNameEng:'Sheriff Chaps'},
      {itemId:39, itemName:'鏢客帽子',ItemNameEng:'Bandit\'s Hat'},
      {itemId:46, itemName:'鏢客襯衫',ItemNameEng:'Bandit\'s Shirt'},
      {itemId:63, itemName:'鏢客褲子',ItemNameEng:'Bandit\'s Pants'},
      {itemId:130, itemName:'鏢客靴子',ItemNameEng:'Bandit\'s Boots'},
      {itemId:21, itemName:'銀行家帽子',ItemNameEng:'Banker\'s Hat'},
      {itemId:26, itemName:'銀行家夾克',ItemNameEng:'Banker\'s Jacket'},
      {itemId:546, itemName:'銀行家靴子',ItemNameEng:'Banker\'s Boots'},
      {itemId:557, itemName:'銀行家褲子',ItemNameEng:'Banker\'s Trousers'},
      {itemId:51, itemName:'開拓者帽子',ItemNameEng:'Frontier Cap'},
      {itemId:75, itemName:'開拓者靴子',ItemNameEng:'Frontier Boots'},
      {itemId:87, itemName:'開拓者背心',ItemNameEng:'Frontier Shirt'},
      {itemId:122, itemName:'開拓者褲子',ItemNameEng:'Frontier Pants'},
      {itemId:368, itemName:'酋長頭飾',ItemNameEng:'Chieftain Headdress'},
      {itemId:369, itemName:'酋長裙子',ItemNameEng:'Chieftain Skirt'},
      {itemId:370, itemName:'酋長衣服',ItemNameEng:'Chieftain Armor'},
      {itemId:371, itemName:'酋長涼鞋',ItemNameEng:'Chieftain Sandals'},
      {itemId:551, itemName:'拿破崙鞋子',ItemNameEng:'Napoleon Boots'},
      {itemId:552, itemName:'拿破崙外套',ItemNameEng:'Napoleon Jacket'},
      {itemId:553, itemName:'拿破崙帽子',ItemNameEng:'Napoleon Hat'},
      {itemId:554, itemName:'拿破崙褲子',ItemNameEng:'Napoleon Leggings'},
      {itemId:334, itemName:'聖誕靴',ItemNameEng:'Santa Boots'},
      {itemId:335, itemName:'聖誕外套',ItemNameEng:'Santa Jacket'},
      {itemId:336, itemName:'聖誕褲子',ItemNameEng:'Santa Pants'},
      {itemId:337, itemName:'聖誕帽子',ItemNameEng:'Santa Hat'},
      {itemId:326, itemName:'雪人鞋',ItemNameEng:'Snowman Boots'},
      {itemId:327, itemName:'雪人外套',ItemNameEng:'Snowman Body'},
      {itemId:328, itemName:'雪人面罩',ItemNameEng:'Snowman Mask'},
      {itemId:329, itemName:'雪人褲子',ItemNameEng:'Snowman Legs'},
      {itemId:321, itemName:'小精靈靴子',ItemNameEng:'Elf Boots'},
      {itemId:323, itemName:'小精靈外套',ItemNameEng:'Elf Vest'},
      {itemId:324, itemName:'小精靈帽子',ItemNameEng:'Elf Hat'},
      {itemId:325, itemName:'小精靈裙子',ItemNameEng:'Elf Skirt'},
      {itemId:360, itemName:'春節舞獅鞋',ItemNameEng:'Chinese Lion Boots'},
      {itemId:361, itemName:'春節舞獅外套',ItemNameEng:'Chinese Lion Vest'},
      {itemId:362, itemName:'春節舞獅面罩',ItemNameEng:'Chinese Lion Hat'},
      {itemId:363, itemName:'春節舞獅褲',ItemNameEng:'Chinese Lion Skirt'},
      {itemId:365, itemName:'舞獅鞋',ItemNameEng:'Prosperous Lion Boots'},
      {itemId:366, itemName:'舞獅外套',ItemNameEng:'Prosperous Lion Body'},
      {itemId:367, itemName:'舞獅面罩',ItemNameEng:'Prosperous Lion Mask'},
      {itemId:372, itemName:'舞獅褲',ItemNameEng:'Prosperous Lion Legs'},
      {itemId:374, itemName:'吉祥舞獅鞋',ItemNameEng:'Lucky Chinese Lion Boots'},
      {itemId:375, itemName:'吉祥舞獅外套',ItemNameEng:'Lucky Chinese Lion Jacket'},
      {itemId:379, itemName:'吉祥舞獅褲',ItemNameEng:'Lucky Chinese Lion Pants'},
      {itemId:380, itemName:'吉祥舞獅面罩',ItemNameEng:'Lucky Chinese Lion Mask'},
      {itemId:448, itemName:'小精靈靴子',ItemNameEng:'Elf Boots'},
      {itemId:449, itemName:'小精靈外套',ItemNameEng:'Elf Vest'},
      {itemId:450, itemName:'小精靈帽子',ItemNameEng:'Elf Hat'},
      {itemId:458, itemName:'小精靈裙子',ItemNameEng:'Elf Skirt'},
      {itemId:459, itemName:'雪人鞋',ItemNameEng:'Snowman Boots'},
      {itemId:461, itemName:'雪人外套',ItemNameEng:'Snowman Body'},
      {itemId:462, itemName:'雪人面罩',ItemNameEng:'Snowman Mask'},
      {itemId:463, itemName:'雪人褲子',ItemNameEng:'Snowman Legs'},
      {itemId:464, itemName:'聖誕靴',ItemNameEng:'Santa Boots'},
      {itemId:465, itemName:'聖誕外套',ItemNameEng:'Santa Jacket'},
      {itemId:466, itemName:'聖誕褲子',ItemNameEng:'Santa Hat'},
      {itemId:467, itemName:'聖誕帽子',ItemNameEng:'Santa Pants'},
      {itemId:481, itemName:'萌兔靴',ItemNameEng:'Easter Boots'},
      {itemId:482, itemName:'萌兔衣',ItemNameEng:'Easter Jacket'},
      {itemId:483, itemName:'萌兔耳',ItemNameEng:'Easter Hat'},
      {itemId:484, itemName:'萌兔褲',ItemNameEng:'Easter Pants'},
      {itemId:487, itemName:'復活節兔靴',ItemNameEng:'Easter Boots'},
      {itemId:489, itemName:'復活節兔夾克',ItemNameEng:'Easter Jacket'},
      {itemId:490, itemName:'復活節兔耳',ItemNameEng:'Easter Hat'},
      {itemId:491, itemName:'復活節兔褲',ItemNameEng:'Easter Pants'},
      {itemId:492, itemName:'傳說兔靴',ItemNameEng:'Easter Boots'},
      {itemId:493, itemName:'傳說兔夾克',ItemNameEng:'Easter Jacket'},
      {itemId:494, itemName:'傳說兔耳',ItemNameEng:'Easter Hat'},
      {itemId:495, itemName:'傳說兔毛褲',ItemNameEng:'Easter Pants'},
      {itemId:24, itemName:'簡易褲子',ItemNameEng:'Simple Pants'},
      {itemId:219, itemName:'簡易頭巾',ItemNameEng:'Simple Bandana'},
      {itemId:283, itemName:'簡易鹿皮鞋',ItemNameEng:'Simple Moccasins'},
      {itemId:663, itemName:'簡易襯衫',ItemNameEng:'Simple Shirt'},
      {itemId:211, itemName:'薩斯科奇馬甲',ItemNameEng:'Sasquatch Chest'},
      {itemId:310, itemName:'薩斯科奇護足',ItemNameEng:'Sasquatch Feet'},
      {itemId:818, itemName:'薩斯科奇面具',ItemNameEng:'Sasquatch Mask'},
      {itemId:819, itemName:'薩斯科奇褲',ItemNameEng:'Sasquatch Legs'},
      {itemId:395, itemName:'軍團士兵褲',ItemNameEng:'Legionnaire Pants'},
      {itemId:396, itemName:'軍團士兵頭盔',ItemNameEng:'Legionnaire Kepi'},
      {itemId:397, itemName:'軍團士兵襯衫',ItemNameEng:'Legionnaire Shirt'},
      {itemId:398, itemName:'軍團士兵鞋',ItemNameEng:'Legionnaire Shoes'},
      {itemId:541, itemName:'先驅者外套',ItemNameEng:'Precursor Body'},
      {itemId:542, itemName:'先驅者帽',ItemNameEng:'Precursor Mask'},
      {itemId:543, itemName:'先驅者褲',ItemNameEng:'Precursor Legs'},
      {itemId:545, itemName:'先驅者靴',ItemNameEng:'Precursor Feet'},
      {itemId:559, itemName:'遊騎兵帽',ItemNameEng:'Ranger\'s Hat'},
      {itemId:560, itemName:'遊騎兵夾克',ItemNameEng:'Ranger\'s Jacket'},
      {itemId:561, itemName:'遊騎兵靴',ItemNameEng:'Ranger\'s Boots'},
      {itemId:562, itemName:'遊騎兵褲',ItemNameEng:'Ranger\'s Trousers'},
      {itemId:565, itemName:'鄉土頭飾',ItemNameEng:'Native Headband'},
      {itemId:566, itemName:'鄉土靴',ItemNameEng:'Native Boots'},
      {itemId:567, itemName:'鄉土襯衫',ItemNameEng:'Native Shirt'},
      {itemId:568, itemName:'鄉土裙',ItemNameEng:'Native Skirt'},
      {itemId:573, itemName:'廚師夾克',ItemNameEng:'Chef\'s Jacket'},
      {itemId:574, itemName:'廚師褲子',ItemNameEng:'Chef\'s Pants'},
      {itemId:575, itemName:'廚師帽子',ItemNameEng:'Chef\'s Hat'},
      {itemId:735, itemName:'朝聖者褲子',ItemNameEng:'Pilgrim Pants'},
      {itemId:736, itemName:'朝聖者帽',ItemNameEng:'Pilgrim Hat'},
      {itemId:737, itemName:'朝聖者外套',ItemNameEng:'Pilgrim Jacket'},
      {itemId:738, itemName:'朝聖者鞋',ItemNameEng:'Pilgrim Shoes'},
      {itemId:740, itemName:'冒險者鞋',ItemNameEng:'Adventurer Shoes'},
      {itemId:741, itemName:'冒險者夾克',ItemNameEng:'Adventurer Jacket'},
      {itemId:742, itemName:'冒險者帽',ItemNameEng:'Adventurer Hat'},
      {itemId:743, itemName:'冒險者褲子',ItemNameEng:'Adventurer Pants'},
      {itemId:744, itemName:'元帥褲',ItemNameEng:'Marshall Pants'},
      {itemId:745, itemName:'元帥帽',ItemNameEng:'Marshall Hat'},
      {itemId:746, itemName:'元帥衣',ItemNameEng:'Marshall Coat'},
      {itemId:747, itemName:'元帥靴',ItemNameEng:'Marshall Boots'},
      {itemId:822, itemName:'將軍裙子',ItemNameEng:'Shogun Skirt'},
      {itemId:823, itemName:'將軍頭飾',ItemNameEng:'Shogun Headdress'},
      {itemId:824, itemName:'將軍木屐',ItemNameEng:'Shogun Geta'},
      {itemId:825, itemName:'將軍和服',ItemNameEng:'Shogun Kimono'},
      {itemId:826, itemName:'航海夾克',ItemNameEng:'Privateer Jacket'},
      {itemId:827, itemName:'航海鞋',ItemNameEng:'Privateer Boots'},
      {itemId:828, itemName:'航海帽',ItemNameEng:'Privateer Tricorn'},
      {itemId:829, itemName:'航海褲',ItemNameEng:'Privateer Pants'},
      {itemId:832, itemName:'錫克教徒褲子',ItemNameEng:'Sikh Pants'},
      {itemId:833, itemName:'錫克教徒頭巾',ItemNameEng:'Sikh Turban'},
      {itemId:834, itemName:'錫克教平底拖鞋',ItemNameEng:'Sikh Babouches'},
      {itemId:835, itemName:'錫克教上衣',ItemNameEng:'Sikh Top'},
      {itemId:628, itemName:'熊貓足',ItemNameEng:'Panda Feet'},
      {itemId:629, itemName:'熊貓身',ItemNameEng:'Panda Body'},
      {itemId:630, itemName:'熊貓腿',ItemNameEng:'Panda Legs'},
      {itemId:631, itemName:'熊貓頭套',ItemNameEng:'Panda Mask'},
      {itemId:635, itemName:'胖胖熊貓足',ItemNameEng:'Fluffy Panda Feet'},
      {itemId:639, itemName:'胖胖熊貓身',ItemNameEng:'Fluffy Panda Body'},
      {itemId:641, itemName:'胖胖熊貓腿',ItemNameEng:'Fluffy Panda Legs'},
      {itemId:642, itemName:'胖胖熊貓頭套',ItemNameEng:'Fluffy Panda Mask'},
      {itemId:651, itemName:'呆萌熊貓足',ItemNameEng:'Wild Panda Feet'},
      {itemId:652, itemName:'呆萌熊貓身',ItemNameEng:'Wild Panda Body'},
      {itemId:655, itemName:'呆萌熊貓腿',ItemNameEng:'Wild Panda Legs'},
      {itemId:659, itemName:'呆萌熊貓頭套',ItemNameEng:'Wild Panda Mask'},
      {itemId:704, itemName:'藤編荷葉足',ItemNameEng:'Lotus Feet'},
      {itemId:705, itemName:'荷葉衣',ItemNameEng:'Lotus Body'},
      {itemId:706, itemName:'荷葉帽',ItemNameEng:'Lotus Hat'},
      {itemId:707, itemName:'荷葉褲',ItemNameEng:'Lotus Legs'},
    ],
    18:[
      {itemId:64, itemName:'皮包',ItemNameEng:'Hide Bag'},
      {itemId:107, itemName:'簡易背包',ItemNameEng:'Simple Backpack'},
      {itemId:330, itemName:'搭車客背包',ItemNameEng:'Hitchhiker\'s Pack'},
      {itemId:331, itemName:'登山包',ItemNameEng:'Mountaineer Bag'},
      {itemId:332, itemName:'大號帆布背包',ItemNameEng:'Large Rucksack'},
      {itemId:333, itemName:'軍用背包',ItemNameEng:'Military Pack'},
      {itemId:442, itemName:'頂級背包',ItemNameEng:'Ultimate Pack'},
      {itemId:539, itemName:'Taptap專屬背包',ItemNameEng:'Hide Bag'},
      {itemId:544, itemName:'遊品位專屬背包',ItemNameEng:'Hide Bag'},
      {itemId:572, itemName:'商人背包',ItemNameEng:'Trader\'s Pack'},
      {itemId:699, itemName:'竹子背包',ItemNameEng:'Bamboo Bag'},
    ],
    17 :[
      {itemId:28, itemName:'旅途特殊獎勵',ItemNameEng:'Biome specific TT Rewards'},
      {itemId:29, itemName:'基礎神秘盒子獎勵',ItemNameEng:'Basic Mystery Box Rewards'},
      {itemId:30, itemName:'神秘盒子稀有物品',ItemNameEng:'Mystery Box Rare Item'},
      {itemId:38, itemName:'神秘盒子稀有配方',ItemNameEng:'Mystery Box Rare Recipes'},
      {itemId:41, itemName:'旅途高級衣服',ItemNameEng:'Biome Premium Clothes'},
      {itemId:77, itemName:'任務所需物品',ItemNameEng:'Needed Quest Item'},
      {itemId:86, itemName:'尋找一隻狗的獎勵',ItemNameEng:'Find for a Dog'},
      {itemId:163, itemName:'廣告獎勵',ItemNameEng:'Advert Rewards'},
      {itemId:251, itemName:'基礎交易獎勵',ItemNameEng:'Basic Trading Time Rewards'},
      {itemId:256, itemName:'賣狗獎勵',ItemNameEng:'Fetch for dogs'},
      {itemId:276, itemName:'需要的製造物品',ItemNameEng:'Needed Crafted Item'},
      {itemId:278, itemName:'任意房屋內機器的材料',ItemNameEng:'Any Machine Input'},
      {itemId:279, itemName:'我房屋內機器製造出的材料',ItemNameEng:'My Machine Output'},
      {itemId:280, itemName:'任意房屋內機器製造出的材料',ItemNameEng:'Any Machine Output'},
      {itemId:281, itemName:'我房屋內機器製造出的材料',ItemNameEng:'My Machine Input'},
      {itemId:468, itemName:'更大的背包',ItemNameEng:'Bigger Backpack'},
      {itemId:469, itemName:'稀有製造材料',ItemNameEng:'Rare Crafting Item'},
      {itemId:840, itemName:'一頂新的帽子',ItemNameEng:'A new hat'},
      {itemId:842, itemName:'稀有配方',ItemNameEng:'Rare recipe'},
      {itemId:843, itemName:'登陸獎勵',ItemNameEng:'Retention'},
    ],
    191:[
      {itemId:43, itemName:'虛擬貨幣',ItemNameEng:'Item_VirtualCurrency'},
      {itemId:140, itemName:'鈔票',ItemNameEng:'Item_Chits'},
      {itemId:226, itemName:'神秘盒子',ItemNameEng:'Item_MysteryBox'},
      {itemId:556, itemName:'船票',ItemNameEng:'FERRY_TICKET'},
      {itemId:671, itemName:'100小鎮金條',ItemNameEng:'Item_GoldBars_03'},
      {itemId:681, itemName:'5小鎮金條',ItemNameEng:'Item_GoldBars_01'},
      {itemId:682, itemName:'20小鎮金條',ItemNameEng:'Item_GoldBars_02'},
    ],
    73:[
      {itemId:56, itemName:'肉卷餡餅',ItemNameEng:'Empanada'},
      {itemId:67, itemName:'肉乾',ItemNameEng:'Jerky'},
      {itemId:89, itemName:'烤肉',ItemNameEng:'Roast Meat'},
      {itemId:94, itemName:'蘋果派',ItemNameEng:'Apple Pie'},
      {itemId:210, itemName:'麵包',ItemNameEng:'Bread'},
      {itemId:252, itemName:'烤XX',ItemNameEng:'Grilled [MAT]'},
      {itemId:307, itemName:'薑餅人',ItemNameEng:'Gingerbread Man'},
      {itemId:308, itemName:'聖誕布丁',ItemNameEng:'Festive Pudding'},
      {itemId:311, itemName:'烤火雞',ItemNameEng:'Roast Turkey'},
      {itemId:381, itemName:'好運餅乾',ItemNameEng:'CNY_FortuneCookie'},
      {itemId:382, itemName:'柚子',ItemNameEng:'CNY_Pomelo'},
      {itemId:387, itemName:'龍蝦派',ItemNameEng:'Crayfish Pie'},
      {itemId:417, itemName:'牧豆薄餅',ItemNameEng:'Mequite Pancakes'},
      {itemId:447, itemName:'壽司',ItemNameEng:'Sushi'},
      {itemId:473, itemName:'土豆',ItemNameEng:'SPD_Potato'},
      {itemId:474, itemName:'愛爾蘭燉菜',ItemNameEng:'SPD_IrishStew'},
      {itemId:496, itemName:'復活節彩蛋',ItemNameEng:'Easter Egg'},
      {itemId:497, itemName:'巨型巧克力兔',ItemNameEng:'Giant Chocolate Bunny'},
      {itemId:503, itemName:'巧克力',ItemNameEng:'Chocolate'},
      {itemId:578, itemName:'煎蛋捲',ItemNameEng:'Omelette'},
      {itemId:579, itemName:'烤蘑菇',ItemNameEng:'Grilled Mushroom'},
      {itemId:580, itemName:'蘋果汁',ItemNameEng:'Apple Juice'},
      {itemId:581, itemName:'香腸',ItemNameEng:'Sausages'},
      {itemId:582, itemName:'蘑菇湯',ItemNameEng:'Mushroom Soup'},
      {itemId:583, itemName:'餅乾',ItemNameEng:'Cookie'},
      {itemId:584, itemName:'魚湯',ItemNameEng:'Fish Soup'},
      {itemId:585, itemName:'炸魚',ItemNameEng:'Fried Fish'},
      {itemId:587, itemName:'黃桃蛋糕',ItemNameEng:'Peach Cake'},
      {itemId:588, itemName:'水牛餡餅',ItemNameEng:'Buffalo Pie'},
    ],
    235:[
      {itemId:236, itemName:'貝殼',ItemNameEng:'Shell'},
      {itemId:384, itemName:'娃卵',ItemNameEng:'Frogspawn'},
      {itemId:385, itemName:'鱷魚鱗片',ItemNameEng:'Crocodile Scales'},
      {itemId:386, itemName:'蜥蜴蛋殼',ItemNameEng:'Reptile Eggshell'},
      {itemId:414, itemName:'恐龍化石',ItemNameEng:'Dinosaur Fossil'},
      {itemId:415, itemName:'仙人掌花',ItemNameEng:'Cactus Flower'},
      {itemId:416, itemName:'綠松石',ItemNameEng:'Turquoise Mineral'},
      {itemId:444, itemName:'海帶',ItemNameEng:'Seaweed'},
      {itemId:445, itemName:'海螺',ItemNameEng:'Seashell'},
      {itemId:446, itemName:'海草',ItemNameEng:'Seaglass'},
      {itemId:498, itemName:'百靈鳥毛',ItemNameEng:'Songbird Feather'},
      {itemId:499, itemName:'蝸牛殼',ItemNameEng:'Snail Shell'},
      {itemId:500, itemName:'翡翠',ItemNameEng:'Emerald Gemstone'},
      {itemId:515, itemName:'松果',ItemNameEng:'Pine Cone'},
      {itemId:516, itemName:'雪絨花',ItemNameEng:'Edelweiss'},
      {itemId:518, itemName:'蟬蛻',ItemNameEng:'Cicada Slough'},
      {itemId:728, itemName:'草原花',ItemNameEng:'Prairie Flower'},
      {itemId:730, itemName:'紅杉果',ItemNameEng:'Sequoia Cone'},
      {itemId:731, itemName:'鱷魚牙',ItemNameEng:'Crocodile Tooth'},
      {itemId:732, itemName:'沙漠玫瑰',ItemNameEng:'Desert Rose'},
      {itemId:733, itemName:'雨林狂花',ItemNameEng:'Jungle Flower'},
      {itemId:734, itemName:'冰',ItemNameEng:'Ice'},
    ],
    221:[
      {itemId:222, itemName:'報紙',ItemNameEng:'Papers'},
      {itemId:223, itemName:'紀念吊墜',ItemNameEng:'Locket'},
    ],
    653:[
      {itemId:34, itemName:'木雕兔子',ItemNameEng:'Carved Rabbit'},
      {itemId:61, itemName:'禿鷲木雕',ItemNameEng:'Carved Vulture'},
      {itemId:62, itemName:'玩具鳥',ItemNameEng:'Toy Bird'},
      {itemId:74, itemName:'玩具浣熊',ItemNameEng:'Toy Raccoon'},
      {itemId:131, itemName:'小號玩具娃娃',ItemNameEng:'Small Toy Doll'},
      {itemId:388, itemName:'追夢人',ItemNameEng:'Ornamental Dreamcatcher'},
      {itemId:389, itemName:'梳子擺件',ItemNameEng:'Ornamental Comb'},
      {itemId:390, itemName:'鱷魚雕刻',ItemNameEng:'Carved Crocodile'},
      {itemId:418, itemName:'玩具老鼠',ItemNameEng:'Toy Rat'},
      {itemId:419, itemName:'仙人掌雕刻',ItemNameEng:'Carved Cactus'},
      {itemId:424, itemName:'石臼',ItemNameEng:'Stone Mortar'},
      {itemId:452, itemName:'美人魚雕刻',ItemNameEng:'Carved Mermaid'},
      {itemId:453, itemName:'玩具蟹',ItemNameEng:'Toy Crab'},
      {itemId:454, itemName:'貝殼項鍊',ItemNameEng:'Seashell Necklace'},
      {itemId:501, itemName:'巨喙鳥玩具',ItemNameEng:'Toucan Toy'},
      {itemId:502, itemName:'翡翠手鐲',ItemNameEng:'Emerald Bracelet'},
      {itemId:505, itemName:'雕刻面具',ItemNameEng:'Carved Mask'},
      {itemId:654, itemName:'木雕',ItemNameEng:'Wooden Carving'},
      {itemId:758, itemName:'半身木雕',ItemNameEng:'Carved Bust'},
      {itemId:759, itemName:'大號玩具娃娃',ItemNameEng:'Large Toy Doll'},
    ],
    189:[
      {itemId:25, itemName:'松樹枝',ItemNameEng:'Pine Stick'},
      {itemId:47, itemName:'樺木',ItemNameEng:'Birch Log'},
      {itemId:76, itemName:'樺樹枝',ItemNameEng:'Birch Stick'},
      {itemId:90, itemName:'松木',ItemNameEng:'Pine Log'},
      {itemId:179, itemName:'牧豆樹枝',ItemNameEng:'Mesquite Stick'},
      {itemId:228, itemName:'牧豆木',ItemNameEng:'Mesquite Log'},
      {itemId:708, itemName:'松木板',ItemNameEng:'Pine Lumber'},
      {itemId:710, itemName:'樺木板',ItemNameEng:'Birch Lumber'},
      {itemId:711, itemName:'牧豆木板',ItemNameEng:'Mesquite Lumber'},
      {itemId:45, itemName:'麻纖維',ItemNameEng:'Hemp Fibre'},
      {itemId:82, itemName:'細繩',ItemNameEng:'Twine'},
      {itemId:110, itemName:'蕁麻纖維',ItemNameEng:'Nettle Fibre'},
      {itemId:237, itemName:'棉纖維',ItemNameEng:'Cotton Fibre'},
      {itemId:48, itemName:'鵝卵石',ItemNameEng:'Sandstone Pebble'},
      {itemId:113, itemName:'燧石',ItemNameEng:'Flint Pebble'},
      {itemId:118, itemName:'石灰石',ItemNameEng:'Limestone Pebble'},
      {itemId:22, itemName:'火雞羽毛',ItemNameEng:'Turkey Feather'},
      {itemId:233, itemName:'鴨毛',ItemNameEng:'Duck Feather'},
      {itemId:234, itemName:'禿鷲毛',ItemNameEng:'Vulture Feather'},
      {itemId:286, itemName:'模具',ItemNameEng:'Moulding'},
      {itemId:287, itemName:'鞣革',ItemNameEng:'Tanned Leather'},
      {itemId:288, itemName:'石瓦',ItemNameEng:'Stone Tile'},
      {itemId:289, itemName:'金屬螺栓',ItemNameEng:'Metal Bolt'},
      {itemId:290, itemName:'紡布',ItemNameEng:'Woven Cloth'},
      {itemId:170, itemName:'鐵礦石',ItemNameEng:'Iron Ore'},
      {itemId:412, itemName:'錫礦石',ItemNameEng:'Tin Ore'},
      {itemId:644, itemName:'錫塊',ItemNameEng:'Tin Nugget'},
      {itemId:645, itemName:'鐵塊',ItemNameEng:'Iron Nugget'},
      {itemId:115, itemName:'海狸皮',ItemNameEng:'Beaver Hide'},
      {itemId:126, itemName:'兔子皮',ItemNameEng:'Rabbit Hide'},
      {itemId:320, itemName:'野豬皮',ItemNameEng:'Boar Hide'},
      {itemId:485, itemName:'野豬毛',ItemNameEng:'Boar Fur Scrap'},
      {itemId:649, itemName:'兔子毛',ItemNameEng:'Rabbit Fur Scrap'},
      {itemId:650, itemName:'海狸毛',ItemNameEng:'Beaver Fur Scrap'},
      {itemId:296, itemName:'野豬皮氈',ItemNameEng:'Boar Felt'},
      {itemId:717, itemName:'海狸皮氈',ItemNameEng:'Beaver Felt'},
      {itemId:718, itemName:'兔毛氈',ItemNameEng:'Rabbit Felt'},
      {itemId:2, itemName:'蘑菇',ItemNameEng:'Mushroom'},
      {itemId:16, itemName:'黑莓',ItemNameEng:'Blackberry'},
      {itemId:42, itemName:'南瓜',ItemNameEng:'Pumpkin'},
      {itemId:116, itemName:'麵粉',ItemNameEng:'Flour'},
      {itemId:133, itemName:'生肉',ItemNameEng:'Raw Meat'},
      {itemId:137, itemName:'蘋果',ItemNameEng:'Apple'},
      {itemId:148, itemName:'甜栗',ItemNameEng:'Sweet Chestnut'},
      {itemId:177, itemName:'小麥草',ItemNameEng:'Wheat Grass'},
      {itemId:268, itemName:'岩鹽',ItemNameEng:'Rock Salt'},
      {itemId:269, itemName:'杜松子',ItemNameEng:'Juniper Berries'},
      {itemId:322, itemName:'鳥蛋',ItemNameEng:'Egg'},
      {itemId:383, itemName:'龍蝦',ItemNameEng:'Crayfish'},
      {itemId:413, itemName:'牧豆豆莢',ItemNameEng:'Mequite Pod'},
      {itemId:425, itemName:'火龍果',ItemNameEng:'Dragon Fruit'},
      {itemId:428, itemName:'蘆筍',ItemNameEng:'Asparagus'},
      {itemId:443, itemName:'蟹鉗',ItemNameEng:'Crab Claw'},
      {itemId:476, itemName:'草莓',ItemNameEng:'Strawberries'},
      {itemId:504, itemName:'可哥豆莢',ItemNameEng:'Cocoa Bean Pod'},
      {itemId:537, itemName:'金蘑菇',ItemNameEng:'Golden Mushroom'},
      {itemId:817, itemName:'仙人掌',ItemNameEng:'Prickly Pear'},
    ],
    184:[
      {itemId:4, itemName:'高級彈弓',ItemNameEng:'Advanced Slingshot'},
      {itemId:15, itemName:'彈弓',ItemNameEng:'Slingshot'},
      {itemId:19, itemName:'複合彈弓',ItemNameEng:'Composite Slingshot'},
      {itemId:270, itemName:'升級版高級彈弓',ItemNameEng:'Upgraded Advanced Slingshot'},
      {itemId:756, itemName:'升級版複合彈弓',ItemNameEng:'Upgraded Composite Slingshot'},
      {itemId:273, itemName:'升級版短柄小斧',ItemNameEng:'Upgraded Hatchet'},
      {itemId:277, itemName:'石斧',ItemNameEng:'Stone Axe'},
      {itemId:346, itemName:'伐木斧',ItemNameEng:'Logger\'s Axe'},
      {itemId:347, itemName:'短柄小斧',ItemNameEng:'Hatchet'},
      {itemId:757, itemName:'升級版伐木斧',ItemNameEng:'Upgraded Logger\'s Axe'},
      {itemId:703, itemName:'超級彈弓',ItemNameEng:'Ultimate Slingshot'},
      {itemId:702, itemName:'超級斧子',ItemNameEng:'Ultimate Axe'},
    ],
    879:[
      {itemId:92, itemName:'圍欄',ItemNameEng:'Bollard Fence'},
      {itemId:96, itemName:'旗幟',ItemNameEng:'Flag 1'},
      {itemId:98, itemName:'旗幟',ItemNameEng:'Flag 2'},
      {itemId:99, itemName:'旗幟',ItemNameEng:'Flag 3'},
      {itemId:100, itemName:'旗幟',ItemNameEng:'Flag 4'},
      {itemId:102, itemName:'旗幟',ItemNameEng:'Flag 5'},
      {itemId:104, itemName:'旗幟',ItemNameEng:'Flag 6'},
      {itemId:106, itemName:'旗幟',ItemNameEng:'Flag 8'},
      {itemId:111, itemName:'垂釣小矮人',ItemNameEng:'Fisher Gnome'},
      {itemId:114, itemName:'馱物小矮人',ItemNameEng:'Carrier Gnome'},
      {itemId:117, itemName:'籬笆',ItemNameEng:'Hedge'},
      {itemId:119, itemName:'五月柱',ItemNameEng:'Maypole'},
      {itemId:120, itemName:'五月柱2',ItemNameEng:'Maypole 2'},
      {itemId:127, itemName:'五月柱3',ItemNameEng:'Maypole 3'},
      {itemId:132, itemName:'五月柱4',ItemNameEng:'Maypole 4'},
      {itemId:134, itemName:'藍色外屋',ItemNameEng:'Blue Outhouse'},
      {itemId:135, itemName:'紅色外屋',ItemNameEng:'Red Outhouse'},
      {itemId:139, itemName:'野豬雕像',ItemNameEng:'Boar Statue'},
      {itemId:145, itemName:'麋鹿雕像',ItemNameEng:'Deer Statue'},
      {itemId:146, itemName:'聖誕樹',ItemNameEng:'Decorated Tree'},
      {itemId:152, itemName:'2號聖誕樹',ItemNameEng:'Decorated Tree 2'},
      {itemId:154, itemName:'3號聖誕樹',ItemNameEng:'Decorated Tree 3'},
      {itemId:159, itemName:'果樹',ItemNameEng:'Fruit Tree'},
      {itemId:160, itemName:'2號果樹',ItemNameEng:'Fruit Tree 2'},
      {itemId:162, itemName:'3號果樹',ItemNameEng:'Fruit Tree 3'},
      {itemId:672, itemName:'小矮人塑像',ItemNameEng:'Gnome'},
      {itemId:673, itemName:'花盆',ItemNameEng:'Flower Pot'},
      {itemId:674, itemName:'大號花盆',ItemNameEng:'Large Flower Pot'},
      {itemId:676, itemName:'路燈',ItemNameEng:'Street Light'},
      {itemId:677, itemName:'小鎮廣告牌',ItemNameEng:'Town Billboard'},
      {itemId:678, itemName:'小鎮噴泉',ItemNameEng:'Town Fountain'},
      {itemId:679, itemName:'水槽',ItemNameEng:'Water Trough'},
      {itemId:680, itemName:'小鎮水井',ItemNameEng:'Town Well'},
    ]

};
