<?php

$config["mycard_channel"] = array(		
	'SW' => '點數卡',
	//--
	'MSN' => '速博數位(SeedNet)',
	'MSO' => 'So-Net',
	'MSH' => '上海銀行WebATM',
	'MLD' => '土地銀行WebATM',
	'7963' => '中國信託WebATM',
	'89021' => '中華郵政WebATM',
	'MHI' => '中華電信839',
	'MHA' => '中華電信HiNet',
	'MHE' => '中華電信市內電話輕鬆付',
	'MFB' => '台北富邦WebATM',
	'MTC' => '台哥大三合一(含東信及泛亞)',
	'MTS' => '台新銀行WebATM',
	'MAQ' => '台灣銀行WebATM',
	'MWA' => '玉山銀行WebATM',
	'MEG' => '兆豐銀行WebATM',
	'MNW' => '安泰代收信用卡',
	'MAP' => '亞太電信',
	'MVB' => '威寶電信',
	'MCA' => '國泰世華 MyATM',
	'MDE' => '第一銀行WebATM',
	'MHB' => '華南銀行WebATM',		
	'MCH' => '彰化銀行WebATM',		
	'MIS' => '遠傳和信電信',		
	'MCT' => '中國信託代收信用卡',		
	'MSK' => '新光銀行WebATM',		
	'PA' => 'PayPal',		
	'MAL' => '支付寶(Alipay)',		
	'MEA' => '支付寶AliPay',		
	'MTB' => '合作金庫WebATM',
	'MCN' => '中國信託實體ATM',
	'MCB' => '中信紅利兌換',
	'MOM' => 'Omypay',
	'MBL' => '快錢',
	'MUP' => '銀聯在線支付',
	'MFE' => '遠傳電信手機版',
);	